export type City = {
  slug: string; city: string; region: string; country: "NL" | "BE" | "DE";
  lang: "NL" | "FR" | "VL" | "DE"; travelTime: string; keyword: string; nlSearches: number; priority: "P1"|"P2"|"P3";
  subAreas: string[]; reviewQuote: string; reviewAuthor: string; reviewCar: string;
  geo: { lat: string; lng: string };
  customH1?: string;
  customMetaTitle?: string;
  customMetaDesc?: string;
  popularBrands?: string[];
  commonJob?: string;
  localFact?: string;
  avgJobDuration?: string;
};

export const CITIES: City[] = [
  { slug:"stuttgart", city:"Stuttgart", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"15-25 Min", keyword:"autoschlüssel nachmachen Stuttgart", nlSearches:2500, priority:"P1", subAreas:["Mitte", "Nord", "Ost", "Süd", "West", "Bad Cannstatt", "Vaihingen", "Feuerbach", "Zuffenhausen"], reviewQuote:"Schlüssel für meinen Mercedes im Zentrum verloren. Innerhalb von 30 Minuten war Hilfe da und ein neuer Schlüssel programmiert. Top Service!", reviewAuthor:"M. Bauer", reviewCar:"Mercedes C-Klasse", geo:{lat:"48.7758",lng:"9.1829"}, customH1:"Autoschlüssel Nachmachen Stuttgart & Autoschlüssel Reparatur", customMetaTitle:"Autoschlüssel Nachmachen Stuttgart Vor Ort | First Class Key", customMetaDesc:"Autoschlüssel nachmachen in Stuttgart? Wir kommen zu Ihnen! Günstiger als der Vertragshändler. 24/7 Notdienst. Rufen Sie jetzt an!", popularBrands:["Mercedes-Benz","Porsche","BMW","Audi","VW"], commonJob:"Smart Key & Keyless Entry Programmierung", localFact:"In Stuttgart, der Heimat von Mercedes-Benz und Porsche, sehen wir täglich Premium-Fahrzeuge, die eine Programmierung auf Händlerniveau erfordern.", avgJobDuration:"30-45 Min" },
  { slug:"sindelfingen", city:"Sindelfingen", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"10-15 Min", keyword:"autoschlüssel nachmachen Sindelfingen", nlSearches:850, priority:"P1", subAreas:["Mitte", "Darmsheim", "Maichingen", "Hinterweil", "Eschenried"], reviewQuote:"Schnelle Hilfe am Stern Center. Mein Audi Schlüssel war defekt, direkt repariert.", reviewAuthor:"T. Wagner", reviewCar:"Audi A4", geo:{lat:"48.7075",lng:"9.0031"}, popularBrands:["Mercedes-Benz","Audi","VW"], commonJob:"Zweitschlüssel programmieren", localFact:"Unser Hauptsitz ist in Sindelfingen. Daher sind wir hier besonders schnell vor Ort – oft schon in unter 15 Minuten.", avgJobDuration:"25-40 Min" },
  { slug:"boeblingen", city:"Böblingen", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"10-20 Min", keyword:"autoschlüssel nachmachen Böblingen", nlSearches:780, priority:"P1", subAreas:["Mitte", "Dagersheim", "Flugfeld", "Tannenberg"], reviewQuote:"Kofferraum versehentlich verschlossen. Wurde beschädigungsfrei geöffnet.", reviewAuthor:"S. Hoffmann", reviewCar:"VW Golf", geo:{lat:"48.6833",lng:"9.0167"}, popularBrands:["VW","Ford","BMW"], commonJob:"Autoöffnung ohne Schlüssel", localFact:"Das Flugfeld Böblingen/Sindelfingen ist ein stark frequentierter Bereich, wo wir oft bei Schlüsselverlust helfen.", avgJobDuration:"20-35 Min" },
  { slug:"ludwigsburg", city:"Ludwigsburg", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"25-35 Min", keyword:"autoschlüssel nachmachen Ludwigsburg", nlSearches:920, priority:"P1", subAreas:["Mitte", "West", "Nord", "Ost", "Süd", "Oßweil", "Hoheneck"], reviewQuote:"Professionell und schnell. Ein neuer Ford-Schlüssel war kein Problem.", reviewAuthor:"K. Müller", reviewCar:"Ford Focus", geo:{lat:"48.8974",lng:"9.1922"}, popularBrands:["VW","Ford","Opel"], commonJob:"Schlüsselgehäuse wechseln & Transponder anlernen", localFact:"In Ludwigsburg gibt es viele Pendler. Ein Zweitschlüssel ist hier sehr gefragt.", avgJobDuration:"30-45 Min" },
  { slug:"esslingen", city:"Esslingen am Neckar", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"30-40 Min", keyword:"autoschlüssel nachmachen Esslingen", nlSearches:810, priority:"P1", subAreas:["Stadtmitte", "Pliensauvorstadt", "Hohenkreuz", "Zell", "Oberesslingen"], reviewQuote:"Sehr netter Kontakt und faire Preise. Viel günstiger als bei BMW.", reviewAuthor:"L. Schmidt", reviewCar:"BMW 5er", geo:{lat:"48.7389",lng:"9.3083"}, popularBrands:["BMW","Audi","Skoda"], commonJob:"BMW Schlüssel programmieren", localFact:"Esslingen hat eine historische Altstadt mit engen Straßen. Wir kommen mit unserem Servicefahrzeug direkt zu Ihnen.", avgJobDuration:"35-50 Min" },
  { slug:"leonberg", city:"Leonberg", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"15-25 Min", keyword:"autoschlüssel nachmachen Leonberg", nlSearches:450, priority:"P1", subAreas:["Mitte", "Eltingen", "Höfingen", "Warmbronn", "Gebersheim"], reviewQuote:"Hat alles wunderbar geklappt, gerne wieder.", reviewAuthor:"P. Becker", reviewCar:"Skoda Octavia", geo:{lat:"48.8016",lng:"9.0122"}, popularBrands:["Skoda","VW","Seat"], commonJob:"Ersatzschlüssel anfertigen", localFact:"Das Leonberger Dreieck ist ein zentraler Verkehrsknotenpunkt. Wir sind schnell da, wenn Sie unterwegs liegenbleiben.", avgJobDuration:"25-40 Min" },
  { slug:"fellbach", city:"Fellbach", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"30-40 Min", keyword:"autoschlüssel nachmachen Fellbach", nlSearches:380, priority:"P2", subAreas:["Fellbach", "Schmiden", "Oeffingen"], reviewQuote:"Super schnell und freundlich.", reviewAuthor:"J. Weber", reviewCar:"Renault Clio", geo:{lat:"48.8086",lng:"9.2758"}, popularBrands:["VW","Renault","Peugeot"], commonJob:"Transponder programmieren", localFact:"Am Rande von Stuttgart sind wir auch in Fellbach Ihr zuverlässiger Partner für Autoschlüssel." },
  { slug:"waiblingen", city:"Waiblingen", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"30-40 Min", keyword:"autoschlüssel nachmachen Waiblingen", nlSearches:350, priority:"P2", subAreas:["Mitte", "Hegnach", "Neustadt", "Bittenfeld"], reviewQuote:"Mein Schlüssel war abgebrochen, wurde sofort erneuert.", reviewAuthor:"A. Klein", reviewCar:"VW Polo", geo:{lat:"48.8322",lng:"9.3175"}, popularBrands:["VW","Opel","Fiat"], commonJob:"Abgebrochenen Schlüssel nachmachen", localFact:"Waiblingen ist schnell über die B14 zu erreichen, sodass wir im Notfall sofort vor Ort sind." },
  { slug:"filderstadt", city:"Filderstadt", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"25-35 Min", keyword:"autoschlüssel nachmachen Filderstadt", nlSearches:410, priority:"P2", subAreas:["Bernhausen", "Bonlanden", "Harthausen", "Plattenhardt", "Sielmingen"], reviewQuote:"Am Flughafen den Schlüssel verloren, Rettung kam in 30 Min.", reviewAuthor:"R. Fischer", reviewCar:"Audi A3", geo:{lat:"48.6667",lng:"9.2167"}, popularBrands:["Audi","BMW","Mercedes-Benz"], commonJob:"Notöffnung am Flughafen Stuttgart", localFact:"Da der Stuttgarter Flughafen in Leinfelden-Echterdingen/Filderstadt liegt, helfen wir oft Urlaubern und Geschäftsreisenden." },
  { slug:"ditzingen", city:"Ditzingen", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"20-30 Min", keyword:"autoschlüssel nachmachen Ditzingen", nlSearches:290, priority:"P2", subAreas:["Mitte", "Heimerdingen", "Hirschlanden", "Schöckingen"], reviewQuote:"Einwandfreie Arbeit.", reviewAuthor:"H. Schulz", reviewCar:"Seat Leon", geo:{lat:"48.8269",lng:"9.0658"}, popularBrands:["Seat","VW","Audi"], commonJob:"Smart Key anlernen", localFact:"Ditzingen liegt verkehrsgünstig an der A81. Wir sind in Kürze bei Ihnen." },
  { slug:"mannheim", city:"Mannheim", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"45-60 Min", keyword:"autoschlüssel nachmachen Mannheim", nlSearches:1200, priority:"P1", subAreas:["Quadrate", "Neckarstadt", "Lindenhof", "Käfertal", "Rheinau"], reviewQuote:"Toller Service am Wasserturm! Mein Autoschlüssel wurde in Rekordzeit nachgemacht.", reviewAuthor:"J. Schmidt", reviewCar:"VW Golf", geo:{lat:"49.4875",lng:"8.4660"}, customH1:"Autoschlüssel Nachmachen Mannheim & Schlüsseldienst", customMetaTitle:"Autoschlüssel Nachmachen Mannheim | 24/7 Mobiler Service", customMetaDesc:"Autoschlüssel verloren in Mannheim? Unser mobiler Schlüsseldienst kommt direkt zu Ihnen. Schnell & günstiger als der Händler. Jetzt anrufen!", popularBrands:["VW","Mercedes-Benz","BMW","Audi"], commonJob:"Smart Key Programmierung", localFact:"In der Quadratestadt Mannheim sind wir aufgrund der guten Anbindung sehr schnell vor Ort.", avgJobDuration:"30-45 Min" },
  { slug:"karlsruhe", city:"Karlsruhe", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"40-55 Min", keyword:"autoschlüssel nachmachen Karlsruhe", nlSearches:1100, priority:"P1", subAreas:["Innenstadt", "Durlach", "Südstadt", "Weststadt", "Mühlburg"], reviewQuote:"Sehr professionell. Ersatzschlüssel für meinen Audi war schnell fertig.", reviewAuthor:"M. Becker", reviewCar:"Audi A3", geo:{lat:"49.0069",lng:"8.4037"}, popularBrands:["Audi","VW","Mercedes-Benz"], commonJob:"Transponder anlernen", localFact:"Als Fächerstadt bekannt, sind wir in Karlsruhe dank der gut ausgebauten Straßen schnell am Einsatzort.", avgJobDuration:"30-45 Min" },
  { slug:"freiburg", city:"Freiburg im Breisgau", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"60-90 Min", keyword:"autoschlüssel nachmachen Freiburg", nlSearches:850, priority:"P2", subAreas:["Altstadt", "Stühlinger", "Wiehre", "Zähringen"], reviewQuote:"Schnelle Hilfe, obwohl mein Auto am Rande von Freiburg stand. Sehr zu empfehlen.", reviewAuthor:"A. Weber", reviewCar:"Ford Fiesta", geo:{lat:"47.9990",lng:"7.8421"}, popularBrands:["Ford","VW","Opel"], commonJob:"Zweitschlüssel fräsen und programmieren", localFact:"Freiburg im Breisgau liegt verkehrsgünstig an der A5, was uns eine zügige Anfahrt ermöglicht.", avgJobDuration:"35-50 Min" },
  { slug:"heidelberg", city:"Heidelberg", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"45-60 Min", keyword:"autoschlüssel nachmachen Heidelberg", nlSearches:800, priority:"P2", subAreas:["Altstadt", "Neuenheim", "Bergheim", "Handschuhsheim"], reviewQuote:"Top Service! Ich stand am Schloss und mein Schlüssel ging nicht mehr.", reviewAuthor:"T. Wagner", reviewCar:"BMW 1er", geo:{lat:"49.3988",lng:"8.6724"}, popularBrands:["BMW","Audi","Mini"], commonJob:"Defekten Autoschlüssel reparieren", localFact:"Die Altstadt von Heidelberg ist eng, aber unsere mobilen Servicefahrzeuge erreichen Sie überall.", avgJobDuration:"25-40 Min" },
  { slug:"heilbronn", city:"Heilbronn", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"30-45 Min", keyword:"autoschlüssel nachmachen Heilbronn", nlSearches:750, priority:"P2", subAreas:["Innenstadt", "Böckingen", "Neckargartach", "Sontheim"], reviewQuote:"Sehr freundlich und kompetent. Mein Autoschlüssel war in wenigen Minuten angelernt.", reviewAuthor:"S. Hoffmann", reviewCar:"Skoda Fabia", geo:{lat:"49.1427",lng:"9.2109"}, popularBrands:["Skoda","VW","Seat"], commonJob:"Autoschlüssel ohne Vorlage nachmachen", localFact:"In der Käthchenstadt Heilbronn sind wir oft bei Schlüsselverlust im Einsatz.", avgJobDuration:"30-45 Min" },
  { slug:"ulm", city:"Ulm", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"45-60 Min", keyword:"autoschlüssel nachmachen Ulm", nlSearches:700, priority:"P2", subAreas:["Mitte", "Söflingen", "Eselsberg", "Wiblingen"], reviewQuote:"Schlüssel im Auto eingesperrt am Münsterplatz. Wurde schadenfrei geöffnet.", reviewAuthor:"L. Fischer", reviewCar:"VW Tiguan", geo:{lat:"48.3984",lng:"9.9916"}, popularBrands:["VW","BMW","Audi"], commonJob:"Auto schadenfrei öffnen", localFact:"Ulm ist durch das Autobahnkreuz Ulm/Elchingen gut an unser Servicegebiet angebunden.", avgJobDuration:"20-35 Min" },
  { slug:"pforzheim", city:"Pforzheim", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"25-40 Min", keyword:"autoschlüssel nachmachen Pforzheim", nlSearches:650, priority:"P2", subAreas:["Innenstadt", "Nordstadt", "Brötzingen", "Eutingen"], reviewQuote:"Ersatzschlüssel für Mercedes gemacht. Funktioniert einwandfrei.", reviewAuthor:"K. Meyer", reviewCar:"Mercedes E-Klasse", geo:{lat:"48.8950",lng:"8.6999"}, popularBrands:["Mercedes-Benz","VW","Ford"], commonJob:"Keyless Go Schlüssel nachmachen", localFact:"Die Goldstadt Pforzheim grenzt direkt an unser Kerngebiet und wird schnell bedient.", avgJobDuration:"30-45 Min" },
  { slug:"reutlingen", city:"Reutlingen", region:"Baden-Württemberg", country:"DE", lang:"DE", travelTime:"30-45 Min", keyword:"autoschlüssel nachmachen Reutlingen", nlSearches:600, priority:"P2", subAreas:["Mitte", "Betzingen", "Ohmenhausen", "Rommelsbach"], reviewQuote:"Besser und schneller als der Händler.", reviewAuthor:"R. Braun", reviewCar:"Opel Astra", geo:{lat:"48.4900",lng:"9.2100"}, popularBrands:["Opel","VW","Skoda"], commonJob:"Wegfahrsperre anlernen", localFact:"Als Großstadt in unmittelbarer Nähe zu Stuttgart gehört Reutlingen zu unserem festen Einzugsgebiet.", avgJobDuration:"25-40 Min" }
];
